-- Generated by Envision Gui2Lua, Version 2.14, 12/25/24.

local Instances = {
	ScreenGui = Instance.new("ScreenGui"),
	_3_UhI_VPQU__ = Instance.new("Frame"),
	Title = Instance.new("TextLabel"),
	Dark = Instance.new("Frame"),
	Example = Instance.new("TextButton"),
	IntroBackground = Instance.new("Frame"),
	Cmdbar = Instance.new("Frame"),
	Input = Instance.new("TextBox"),
	bigdih = Instance.new("TextButton"),
	Icon = Instance.new("ImageLabel"),
	ButtonLabel = Instance.new("TextLabel"),
	dih_2 = Instance.new("TextButton"),
	Icon_2 = Instance.new("ImageLabel"),
	ButtonLabel_2 = Instance.new("TextLabel"),
}

Instances.ScreenGui.Name = "ScreenGui"
Instances.ScreenGui.Parent = game:GetService("CoreGui")

Instances._3_UhI_VPQU__.Name = "3\UhI#VPQU\,"
Instances._3_UhI_VPQU__.Active = true
Instances._3_UhI_VPQU__.ZIndex = 10
Instances._3_UhI_VPQU__.Size = UDim2.new(0, 338, 0, 122)
Instances._3_UhI_VPQU__.BorderSizePixel = 0
Instances._3_UhI_VPQU__.Position = UDim2.new(0.542000294, -250, 0.675959885, -220)
Instances._3_UhI_VPQU__.BackgroundColor3 = Color3.new(0, 0, 0)
Instances._3_UhI_VPQU__.Parent = Instances.ScreenGui

Instances.Title.Name = "Title"
Instances.Title.Active = true
Instances.Title.ZIndex = 10
Instances.Title.Size = UDim2.new(0, 338, 0, 20)
Instances.Title.BorderSizePixel = 0
Instances.Title.BackgroundColor3 = Color3.new(0, 0, 0)
Instances.Title.TextColor3 = Color3.new(1, 1, 1)
Instances.Title.Text = "Infinite Yield FE - Key System"
Instances.Title.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.Title.Parent = Instances._3_UhI_VPQU__

Instances.Dark.Name = "Dark"
Instances.Dark.Active = true
Instances.Dark.ZIndex = 10
Instances.Dark.Size = UDim2.new(0, 338, 0, 77)
Instances.Dark.BorderSizePixel = 0
Instances.Dark.Position = UDim2.new(0, 0, 0, 45)
Instances.Dark.BackgroundColor3 = Color3.new(0, 0, 0)
Instances.Dark.Parent = Instances._3_UhI_VPQU__

Instances.Example.Name = "Example"
Instances.Example.AutoButtonColor = true
Instances.Example.Visible = false
Instances.Example.ZIndex = 10
Instances.Example.Size = UDim2.new(0, 256, 0, 20)
Instances.Example.BorderSizePixel = 0
Instances.Example.BackgroundTransparency = 1
Instances.Example.TextColor3 = Color3.new(1, 1, 1)
Instances.Example.Text = "Example"
Instances.Example.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.Example.TextXAlignment = Enum.TextXAlignment.Left
Instances.Example.Parent = Instances._3_UhI_VPQU__

Instances.IntroBackground.Name = "IntroBackground"
Instances.IntroBackground.Active = true
Instances.IntroBackground.ZIndex = 10
Instances.IntroBackground.Size = UDim2.new(0, 338, 0, 77)
Instances.IntroBackground.BorderSizePixel = 0
Instances.IntroBackground.Position = UDim2.new(0, 0, 0, 45)
Instances.IntroBackground.BackgroundColor3 = Color3.new(0, 0, 0)
Instances.IntroBackground.Parent = Instances._3_UhI_VPQU__

Instances.Cmdbar.Name = "Cmdbar"
Instances.Cmdbar.ZIndex = 10
Instances.Cmdbar.Size = UDim2.new(0, 324, 0, 25)
Instances.Cmdbar.ClipsDescendants = true
Instances.Cmdbar.BorderSizePixel = 0
Instances.Cmdbar.BackgroundTransparency = 1
Instances.Cmdbar.Position = UDim2.new(0, 5, 0, 20)
Instances.Cmdbar.Parent = Instances._3_UhI_VPQU__

Instances.Input.Name = "Input"
Instances.Input.ZIndex = 10
Instances.Input.Size = UDim2.new(1, -2, 1, 0)
Instances.Input.BorderSizePixel = 0
Instances.Input.BackgroundTransparency = 1
Instances.Input.Position = UDim2.new(0, 2, 0, 0)
Instances.Input.CursorPosition = -1
Instances.Input.PlaceholderText = "Key"
Instances.Input.TextColor3 = Color3.new(1, 1, 1)
Instances.Input.Text = ""
Instances.Input.TextXAlignment = Enum.TextXAlignment.Left
Instances.Input.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.Input.Parent = Instances.Cmdbar

Instances.bigdih.Name = "bigdih"
Instances.bigdih.AutoButtonColor = true
Instances.bigdih.ZIndex = 10
Instances.bigdih.Size = UDim2.new(1, -10, 0, 25)
Instances.bigdih.BorderSizePixel = 0
Instances.bigdih.Position = UDim2.new(0, 5, 0, 55)
Instances.bigdih.BackgroundColor3 = Color3.new(0, 0, 0)
Instances.bigdih.Text = ""
Instances.bigdih.Parent = Instances._3_UhI_VPQU__

Instances.Icon.Name = "Icon"
Instances.Icon.ZIndex = 10
Instances.Icon.Size = UDim2.new(0, 16, 0, 16)
Instances.Icon.BackgroundTransparency = 1
Instances.Icon.Position = UDim2.new(0, 5, 0, 5)
Instances.Icon.Image = "rbxassetid://4911962991"
Instances.Icon.ImageContent = Content
Instances.Icon.Parent = Instances.bigdih

Instances.ButtonLabel.Name = "ButtonLabel"
Instances.ButtonLabel.ZIndex = 10
Instances.ButtonLabel.Size = UDim2.new(1, -28, 1, 0)
Instances.ButtonLabel.BackgroundTransparency = 1
Instances.ButtonLabel.Position = UDim2.new(0, 28, 0, 0)
Instances.ButtonLabel.TextColor3 = Color3.new(1, 1, 1)
Instances.ButtonLabel.Text = "Submit"
Instances.ButtonLabel.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.ButtonLabel.TextXAlignment = Enum.TextXAlignment.Left
Instances.ButtonLabel.Parent = Instances.bigdih

Instances.dih_2.Name = "dih"
Instances.dih_2.AutoButtonColor = true
Instances.dih_2.ZIndex = 10
Instances.dih_2.Size = UDim2.new(1, -10, 0, 25)
Instances.dih_2.BorderSizePixel = 0
Instances.dih_2.Position = UDim2.new(0, 5, 0, 85)
Instances.dih_2.BackgroundColor3 = Color3.new(0, 0, 0)
Instances.dih_2.Text = ""
Instances.dih_2.Parent = Instances._3_UhI_VPQU__

Instances.Icon_2.Name = "Icon"
Instances.Icon_2.ZIndex = 10
Instances.Icon_2.Size = UDim2.new(0, 16, 0, 16)
Instances.Icon_2.BackgroundTransparency = 1
Instances.Icon_2.Position = UDim2.new(0, 5, 0, 5)
Instances.Icon_2.Image = "rbxassetid://129697930"
Instances.Icon_2.ImageContent = Content
Instances.Icon_2.Parent = Instances.dih_2

Instances.ButtonLabel_2.Name = "ButtonLabel"
Instances.ButtonLabel_2.ZIndex = 10
Instances.ButtonLabel_2.Size = UDim2.new(1, -28, 1, 0)
Instances.ButtonLabel_2.BackgroundTransparency = 1
Instances.ButtonLabel_2.Position = UDim2.new(0, 28, 0, 0)
Instances.ButtonLabel_2.TextColor3 = Color3.new(1, 1, 1)
Instances.ButtonLabel_2.Text = "Get Key"
Instances.ButtonLabel_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.ButtonLabel_2.TextXAlignment = Enum.TextXAlignment.Left
Instances.ButtonLabel_2.Parent = Instances.dih_2

-- Function "StarterGui.ScreenGui.3\UhI#VPQU\,.bigdih.LocalScript"
coroutine.wrap(function()
	local script = Instance.new("LocalScript", Instances.bigdih)
	script.Parent.MouseButton1Click:Connect(function()
		if script.Parent.Parent.Cmdbar.Input.Text=="" then
			script.Parent.Parent.Cmdbar.Input.Text="Invalid key.";
		else
			script.Parent.Parent.Cmdbar.Input.Text="Please do not bypass the linkvertise."
			script.Parent.Parent.Cmdbar.Input.TextColor3=Color3.new(154, 0, 0)
			local s=Instance.new("Message",workspace)
			s.Text="If you did not bypass, please join our support server \nfor a free key (must show proof): https://discord.gg/sgVdHRbZkm"
			setclipboard("https://discord.gg/sgVdHRbZkm")
			task.wait(0.5)
			script.Parent.Parent.Cmdbar.Input.Text=""
			script.Parent.Parent.Cmdbar.Input.TextColor3=Color3.new(255,255,255)
		end
	end)
end)()

-- Function "StarterGui.ScreenGui.3\UhI#VPQU\,.dih.LocalScript"
coroutine.wrap(function()
	local script = Instance.new("LocalScript", Instances.dih_2)
	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Text="Copied to clipboard"
		setclipboard("https://linkvertise.com/1356524/36XF7oPmKTUO?o=sharing")
		task.wait(0.5)
		script.Parent.Text="Get Key"
	end)
end)()

--[[ End of generation. ]]
